amcl:
  ros__parameters:
    use_map_topic: true
    base_frame_id: base_link
    odom_frame_id: odom
    scan_topic: scan
    tf_broadcast: true
    max_particles: 2000
    min_particles: 500
    update_min_d: 0.1
    update_min_a: 0.05

map_server:
  ros__parameters:
    yaml_filename: /home/robot/maps/home.yaml

planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.25

controller_server:
  ros__parameters:
    controller_frequency: 15.0
    controller_plugins: ["DWB"]
    DWB:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: 0.0
      max_vel_x: 0.6
      acc_lim_x: 0.8
      acc_lim_theta: 1.2
      vx_samples: 20
      vy_samples: 0
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      xy_goal_tolerance: 0.15
      yaw_goal_tolerance: 0.15

bt_navigator:
  ros__parameters:
    default_bt_xml_filename: "navigate_w_replanning_time.xml"
    plugin_lib_names: ["nav2_behavior_tree::NavigateToPoseAction", "nav2_behavior_tree::Spin", "nav2_behavior_tree::Wait"]

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 0.1

costmap_common:
  footprint: [[0.25, 0.20], [0.25, -0.20], [-0.25, -0.20], [-0.25, 0.20]]
  inflation_layer.inflation_radius: 0.6
  obstacle_layer.max_obstacle_height: 0.35
  obstacle_layer.combination_method: 1
  observation_sources: scan
  scan:
    topic: scan
    clearing: true
    marking: true
    data_type: LaserScan

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 5.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 4.0
      height: 4.0
      resolution: 0.05
      plugins: ["obstacle_layer", "inflation_layer"]

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 2.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_maximum: false
      resolution: 0.05
      plugins: ["obstacle_layer", "inflation_layer"]

lifecycle_manager:
  ros__parameters:
    autostart: true
    node_names: ["map_server", "amcl", "planner_server", "controller_server", "bt_navigator", "smoother_server"]
