---
version: 1.0
kind: personal_robot_assistant

identity:
  name: "TestBot"
  designation: "PRA-T01"
  platform_version: "v0.0.1"

hardware:
  base: "Test Platform"
  arm: "None"
  compute: "Test CPU"

sensors:
  cameras:
    type: "stub"
    topics: []
  lidar:
    type: "stub"
    topic: "/sensors/lidar"

boot_prompts:
  system_prompt: >
    This is a test config for CI validation.
  success_criteria:
    - "Validates against schema"
    - "Triggers autobump"